# Generated by Django 4.0.4 on 2022-08-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring', '0002_customuser_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='communication',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Способ связи'),
        ),
    ]
