# Generated by Django 4.0.4 on 2022-08-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring', '0004_alter_customuser_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='communication',
            field=models.CharField(blank=True, default='Не вказано', max_length=256, verbose_name='Способ связи'),
        ),
    ]
