# Generated by Django 4.0.4 on 2022-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring', '0006_alter_customuser_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
    ]
